
REGION = "AMERICAS"
MY_REGION = "NA1"
SZN_START = 1668623400

# Normalization constants(unused)
MAX_KILLS = 30
MAX_DEATHS = 20
MAX_ASSISTS = 40
MAX_CS = 12
MAX_MASTERY = 5000000

# Binning constants
MASTERY_BINS = 6
KILL_BINS = 10
DEATH_BINS = 10
ASSIST_BINS = 10
CS_BINS = 12

RANK_BINS = 23
GOLD_BINS = ...
VISION_BINS = 8
TIME_DEAD_BINS = ...
TOTAL_DMG_BINS = ...
TOTAL_DMG_TAKEN_BINS = ...

# globals
home = None

# champ/skin info
SKINS = {}
CHAMPION_MAPPING = {}